%% Lowess & Custom Models 
% David Li

function [fitresult, gof] = createFits(Propofol, Remifentanil, Algometry)
%CREATEFITS(PROPOFOL,REMIFENTANIL,ALGOMETRY)
%  Create fits.
%
%  Data for 'Custome Model' fit:
%      X Input : Propofol
%      Y Input : Remifentanil
%      Z Output: Algometry
%  Data for 'Lowess' fit:
%      X Input : Propofol
%      Y Input : Remifentanil
%      Z Output: Algometry
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 09-Dec-2018 20:43:07

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Custome Model'.
[xData, yData, zData] = prepareSurfaceData( Propofol, Remifentanil, Algometry );

% Set up fittype and options.
ft = fittype( 'combinedEffect(x, y, IC50A, IC50B, alpha, n)', 'independent', {'x', 'y'}, 'dependent', 'z' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 -Inf -Inf];
opts.StartPoint = [0.8192 0.1213 0.482 0.4345];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( [xData, yData], zData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Custome Model' );

% Plot fit with data.
subplot( 2, 2, 2 );
h = plot( fitresult{1}, [xData, yData], zData );
legend( h, 'Custome Model', 'Algometry vs. Propofol, Remifentanil', 'Location', 'NorthEast' );
% Label axes
xlabel Propofol
ylabel Remifentanil
zlabel Algometry
grid on

% Plot residuals.
subplot( 2, 2, 4 );
h = plot( fitresult{1}, [xData, yData], zData, 'Style', 'Residual' );
legend( h, 'Custome Model - residuals', 'Location', 'NorthEast' );
% Label axes
xlabel Propofol
ylabel Remifentanil
zlabel Algometry
grid on

% Make contour plot.
subplot( 1, 2, 1 );
h = plot( fitresult{1}, [xData, yData], zData, 'Style', 'Contour' );
legend( h, 'Custome Model', 'Algometry vs. Propofol, Remifentanil', 'Location', 'NorthEast' );
% Label axes
xlabel Propofol
ylabel Remifentanil
grid on

%% Fit: 'Lowess'.
[xData, yData, zData] = prepareSurfaceData( Propofol, Remifentanil, Algometry );

% Set up fittype and options.
ft = fittype( 'lowess' );
opts = fitoptions( 'Method', 'LowessFit' );
opts.Normalize = 'on';
opts.Span = 0.4;

% Fit model to data.
[fitresult{2}, gof(2)] = fit( [xData, yData], zData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'Lowess' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{2}, [xData, yData], zData );
legend( h, 'Lowess', 'Algometry vs. Propofol, Remifentanil', 'Location', 'NorthEast' );
% Label axes
xlabel Propofol
ylabel Remifentanil
zlabel Algometry
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{2}, [xData, yData], zData, 'Style', 'Residual' );
legend( h, 'Lowess - residuals', 'Location', 'NorthEast' );
% Label axes
xlabel Propofol
ylabel Remifentanil
zlabel Algometry
grid on
